.......F
======================================================================
FAIL: test_uses_list_template (lists.tests.ListViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hadesshark/note-and-code/code/python/TDD/superlists/lists/tests.py", line 71, in test_uses_list_template
    self.assertTemplateUsed(response, 'list.html')
  File "/usr/local/lib/python3.5/site-packages/django/test/testcases.py", line 543, in assertTemplateUsed
    (template_name, ', '.join(template_names)))
AssertionError: False is not true : Template 'list.html' was not a template used to render the response. Actual template(s) used: home.html

----------------------------------------------------------------------
Ran 8 tests in 0.028s

FAILED (failures=1)
