E
======================================================================
ERROR: test_can_start_a_list_and_retrieve_it_later (__main__.NewVisitorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "functional_tests.py", line 27, in test_can_start_a_list_and_retrieve_it_later
    inputbox.get_attribute('placeholder'),
NameError: name 'inputbox' is not defined

----------------------------------------------------------------------
Ran 1 test in 3.665s

FAILED (errors=1)
